# Generated by Django 5.2.9 on 2026-05-31 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='事業者番号')),
                ('client_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='事業者名称')),
                ('client_name_kana', models.CharField(blank=True, max_length=40, null=True, verbose_name='事業者名称カナ')),
                ('client_rep_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='代表者名称')),
                ('client_cls', models.CharField(blank=True, max_length=1, null=True, verbose_name='事業者区分')),
                ('client_zip_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='郵便番号')),
                ('client_address1', models.CharField(blank=True, max_length=60, null=True, verbose_name='住所１')),
                ('client_address2', models.CharField(blank=True, max_length=60, null=True, verbose_name='住所２')),
                ('client_phone_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('client_fax_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='FAX')),
                ('storage_volume', models.FloatField(blank=True, null=True, verbose_name='M容量')),
                ('ecoDocuments_client_flg', models.CharField(blank=True, max_length=1, null=True, verbose_name='なんでも書庫使用区分')),
                ('ecoEstimate_client_flg', models.CharField(blank=True, max_length=1, null=True, verbose_name='eco見積使用区分')),
                ('ecoContract_client_flg', models.CharField(blank=True, max_length=1, null=True, verbose_name='eco受注使用区分')),
                ('fiscalYear', models.CharField(blank=True, max_length=4, null=True, verbose_name='会計年度')),
                ('fiscalYearFlg', models.CharField(blank=True, max_length=1, null=True, verbose_name='会計年度表示区分')),
                ('fiscalYearFrom', models.CharField(blank=True, max_length=10, null=True, verbose_name='事業年度開始日')),
                ('fiscalMonthFlg', models.CharField(blank=True, max_length=10, null=True, verbose_name='月度表示区分')),
                ('create_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='作成者')),
                ('update_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='更新者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estimate_year', models.CharField(blank=True, max_length=4, null=True, verbose_name='estimate year')),
                ('estimate_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='estimate no')),
                ('estimate_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='estimate name')),
            ],
            options={
                'db_table': 'estimate',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_no', models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='unit No')),
                ('unit_name', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='unit name')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='CurrentClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client', verbose_name='顧問先')),
                ('customUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='利用者')),
            ],
            options={
                'db_table': 'currentClient',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_no', models.CharField(blank=True, max_length=13, null=True, verbose_name='得意先管理番号')),
                ('customer_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='得意先名称')),
                ('customer_short_name', models.CharField(blank=True, max_length=14, null=True, verbose_name='得意先略称')),
                ('customer_kana', models.CharField(blank=True, max_length=14, null=True, verbose_name='得意先カナ')),
                ('customer_zip_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='郵便番号')),
                ('customer_address1', models.CharField(blank=True, max_length=60, null=True, verbose_name='住所１')),
                ('customer_address2', models.CharField(blank=True, max_length=60, null=True, verbose_name='住所２')),
                ('customer_phone_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('customer_personal_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='携帯電話番号')),
                ('customer_fax_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='FAX')),
                ('customer_person', models.CharField(blank=True, max_length=30, null=True, verbose_name='担当者名')),
                ('group_cls', models.CharField(blank=True, max_length=1, null=True, verbose_name='グループ')),
                ('payment_close_date', models.CharField(blank=True, max_length=2, null=True, verbose_name='請求締め日')),
                ('payment_sight', models.CharField(blank=True, max_length=10, null=True, verbose_name='請求サイト')),
                ('payment_payday', models.CharField(blank=True, max_length=2, null=True, verbose_name='入金予定日')),
                ('payment_limit_date', models.CharField(blank=True, max_length=2, null=True, verbose_name='請求書提出期限')),
                ('customer_bank', models.CharField(blank=True, max_length=20, null=True, verbose_name='銀行コード')),
                ('customer_branch', models.CharField(blank=True, max_length=20, null=True, verbose_name='支店コード')),
                ('customer_bank_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='口座番号')),
                ('customer_bank_holder', models.CharField(blank=True, max_length=20, null=True, verbose_name='名義人名')),
                ('client_flg', models.CharField(blank=True, max_length=1, null=True, verbose_name=' 顧客区分')),
                ('sales_flg', models.CharField(blank=True, max_length=1, null=True, verbose_name='営業対象')),
                ('use_flg', models.CharField(blank=True, choices=[('0', '利用中'), ('9', '停止')], default='0', max_length=1, null=True, verbose_name='利用状況')),
                ('create_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='作成者')),
                ('update_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='更新者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client', verbose_name='事業者')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='明細名称')),
                ('material_dimensions', models.CharField(blank=True, max_length=50, null=True, verbose_name='材質・寸法')),
                ('budget_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='予算数量')),
                ('budget_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='予算単価')),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='予算金額')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='見積数量')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='見積単価')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='見積金額')),
                ('markup_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='掛率')),
                ('calcu_cls', models.CharField(blank=True, default='0', null=True, verbose_name='計算区分')),
                ('sort_order', models.IntegerField(default=0)),
                ('estimate_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.estimate')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.task')),
                ('budget_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.unit', verbose_name='予算単位')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.unit', verbose_name='見積単位')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detail_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='明細名称')),
                ('calcu_cls', models.CharField(blank=True, default='0', null=True, verbose_name='計算区分')),
                ('budget_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='予算単価')),
                ('sort_order', models.IntegerField(default=0)),
                ('unit_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.unit', verbose_name='予算単位')),
            ],
            options={
                'db_table': 'reference',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_no', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='担当者番号')),
                ('user_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='担当者名称')),
                ('use_flg', models.CharField(blank=True, choices=[('0', '利用中'), ('9', '停止')], default='0', max_length=1, null=True, verbose_name='利用状況')),
                ('salesman_flg', models.CharField(max_length=1, verbose_name='営業職')),
                ('manager_flg', models.CharField(max_length=1, verbose_name='現場管理職')),
                ('create_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='作成者')),
                ('update_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='更新者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client', verbose_name='事業者')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
