# Generated by Django 5.2.9 on 2026-03-30 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estimate_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='estimate no')),
                ('estimate_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='estimate name')),
            ],
            options={
                'db_table': 'estimate',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.IntegerField(blank=True, null=True, unique=True, verbose_name='unit No')),
                ('unit_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='unit name')),
            ],
            options={
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='明細名称')),
                ('tree_seq', models.CharField(blank=True, max_length=50, null=True)),
                ('budget_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='予算数量')),
                ('budget_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='予算単価')),
                ('budget_amount', models.IntegerField(blank=True, null=True, verbose_name='予算金額')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='予算数量')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='予算単価')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='予算金額')),
                ('markup_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='掛け率')),
                ('calcu_cls', models.CharField(blank=True, null=True, verbose_name='計算区分')),
                ('sort_order', models.IntegerField(default=0)),
                ('estimate_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.estimate')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.task')),
                ('budget_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.unit', verbose_name='予算単位')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.unit', verbose_name='予算単位')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='明細名称')),
                ('calcu_cls', models.CharField(blank=True, default='0', null=True, verbose_name='計算区分')),
                ('budget_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='予算単価')),
                ('unit_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.unit', verbose_name='予算単位')),
            ],
            options={
                'db_table': 'reference',
            },
        ),
    ]
