# Generated by Django 5.2.13 on 2026-06-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_account_type',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='預金種目'),
        ),
    ]
