# Generated by Django 5.2.13 on 2026-06-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='segment_no',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='部門コード'),
        ),
    ]
