# Generated by Django 5.2.13 on 2026-06-24 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='fiscalyear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.fiscalyear', verbose_name='受注年度'),
        ),
    ]
