# Generated by Django 5.2.9 on 2026-03-30 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tree_seq',
        ),
    ]
