# Generated by Django 5.2.9 on 2025-12-22 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='estimate name'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='estimate no'),
        ),
        migrations.AlterField(
            model_name='estimated',
            name='estimate_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.estimate', verbose_name='estimate no'),
        ),
    ]
