# Generated by Django 5.2.9 on 2026-06-08 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('process_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='工種名称')),
                ('calcu_cls', models.CharField(blank=True, default='0', null=True, verbose_name='計算区分')),
                ('budget_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='予算単価')),
                ('sort_order', models.IntegerField(default=0)),
                ('unit_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.unit', verbose_name='予算単位')),
            ],
            options={
                'db_table': 'process',
            },
        ),
    ]
