# Generated by Django 5.2.9 on 2026-04-02 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_task_tree_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='見積金額'),
        ),
        migrations.AlterField(
            model_name='task',
            name='markup_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='掛率'),
        ),
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='見積単価'),
        ),
        migrations.AlterField(
            model_name='task',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='見積数量'),
        ),
        migrations.AlterField(
            model_name='task',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.unit', verbose_name='見積単位'),
        ),
    ]
