# Generated by Django 5.2.9 on 2025-12-24 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_estimate_estimate_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.IntegerField(blank=True, null=True, verbose_name='unit No')),
                ('unit_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='unit nmae')),
            ],
            options={
                'db_table': 'unit',
            },
        ),
        migrations.AlterField(
            model_name='estimated',
            name='estimate_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.estimate'),
        ),
        migrations.AlterField(
            model_name='estimated',
            name='budget_unit',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, related_name='unit1', to='app.unit', verbose_name='予算単位'),
            preserve_default=False,
        ),
    ]
