# Generated by Django 5.2.9 on 2026-06-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='calcu_cls',
            field=models.CharField(blank=True, default='0', max_length=2, null=True, verbose_name='計算区分'),
        ),
    ]
