# Generated by Django 5.2.13 on 2026-06-25 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_customer_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_account_type',
            new_name='customer_deposit_cls',
        ),
    ]
