# Generated by Django 5.2.13 on 2026-06-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_segment_segment_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aggregation_no', models.CharField(blank=True, max_length=2, null=True, verbose_name='集計区分番号')),
                ('aggregation_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='集計区分名称')),
                ('calcu_cls', models.CharField(blank=True, default='0', max_length=2, null=True, verbose_name='計算区分')),
                ('create_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='作成者')),
                ('update_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='更新者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'aggregation',
            },
        ),
    ]
