# Generated by Django 5.2.9 on 2026-06-26 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_customer_account_type_customer_customer_deposit_cls'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='construction_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.construction', verbose_name='請負形態'),
        ),
    ]
