# Generated by Django 5.2.9 on 2026-06-08 03:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_process_calcu_cls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='unit',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client', verbose_name='事業者'),
        ),
        migrations.AddField(
            model_name='unit',
            name='create_user',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='update_user',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
