# Generated by Django 5.2.9 on 2025-12-24 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_unit_alter_estimated_estimate_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimated',
            name='budget_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit1', to='app.unit', verbose_name='予算単位'),
        ),
    ]
