# Generated by Django 5.2.13 on 2026-06-23 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aggregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client', verbose_name='事業者'),
        ),
    ]
