# Generated by Django 5.2.9 on 2026-04-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_task_amount_alter_task_markup_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='material_dimensions',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='材質・寸法'),
        ),
    ]
