# Generated by Django 5.2.13 on 2026-06-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_unit_sort_order_unit_client_unit_create_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_no',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='unit No'),
        ),
    ]
