# Generated by Django 5.2.9 on 2026-06-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_estimate_construction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='markup_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='掛率'),
        ),
    ]
