# Generated by Django 5.2.9 on 2025-12-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_estimated_budget_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
