# Generated by Django 5.2.13 on 2026-04-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_material_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
