# Generated by Django 5.2.13 on 2026-05-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_task_amount_alter_task_budget_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=14, null=True, verbose_name='見積金額'),
        ),
        migrations.AlterField(
            model_name='task',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=14, null=True, verbose_name='予算金額'),
        ),
    ]
