# Generated by Django 5.2.13 on 2026-06-23 05:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_aggregation_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client', verbose_name='事業者'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='consumption_cls',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='消費税区分'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='consumption_rate',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='消費税率'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='contract_address1',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='現場住所１'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='contract_address2',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='現場住所２'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='contract_zip_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='現場郵便番号'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='create_user',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimate',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.customer', verbose_name='得意先'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='受渡場所'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='税抜見積金額'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_branch_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='工事枝番名称'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_branch_no',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='見積書枝番号'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='実行予算'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_cls',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='請負形態区分'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='見積年月日'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_end_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='工事完成予定日'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_limit_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='見積有効期限'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.user', verbose_name='見積担当者'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_print_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='見積書作成日'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_profit',
            field=models.IntegerField(blank=True, null=True, verbose_name='工事利益'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_start_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='工事開始予定日'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_status',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='受注状態区分'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_tax_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='消費税額'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='orderer_name1',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='発注者名上段'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='orderer_name2',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='発注者名下段'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='orderer_person',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='発注担当者'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='orderer_representative',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='発注者代表者'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='payment_term',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='支払条件'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.segment', verbose_name='部門'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='summary',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='update_user',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='工事名称'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_no',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='見積書番号'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_year',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='受注年度'),
        ),
    ]
