# Generated by Django 5.2.9 on 2026-06-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_unit_unit_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='use_flg',
            field=models.CharField(blank=True, choices=[('0', '使用する'), ('9', '使用しない')], default='0', max_length=1, null=True, verbose_name='利用状況'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='use_flg',
            field=models.CharField(blank=True, choices=[('0', '使用する'), ('9', '使用しない')], default='0', max_length=1, null=True, verbose_name='利用状況'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='unit name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='use_flg',
            field=models.CharField(blank=True, choices=[('0', '使用する'), ('9', '使用しない')], default='0', max_length=1, null=True, verbose_name='利用状況'),
        ),
    ]
