# Generated by Django 5.2.13 on 2026-04-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
