# Generated by Django 5.2.9 on 2025-12-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_estimate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estimated',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
