# Generated by Django 5.2.9 on 2026-06-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_estimate_markup_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_date',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='見積年月日'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_end_date',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='工事完成予定日'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_limit_date',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='見積有効期限'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_start_date',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='工事開始予定日'),
        ),
    ]
