# Generated by Django 5.2.9 on 2026-06-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_estimate_estimate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_print_date',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='見積書作成日'),
        ),
    ]
