# Generated by Django 5.2.13 on 2026-05-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_task_amount_alter_task_budget_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='budget_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='予算金額'),
        ),
    ]
