# Generated by Django 5.2.13 on 2026-06-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_unit_use_flg_alter_customer_use_flg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_short_name',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='担当者略称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_no',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='担当者番号'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
