# Generated by Django 5.2.9 on 2026-04-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='estimate_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='estimate year'),
        ),
    ]
