# Generated by Django 5.2.9 on 2026-01-08 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_estimate_id_alter_estimated_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimated',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='estimated',
            name='position',
        ),
    ]
