# Generated by Django 5.2.9 on 2026-05-05 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_estimate_estimate_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='calcu_cls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.reference', verbose_name='計算区分'),
        ),
    ]
