# Generated by Django 5.2.9 on 2026-01-08 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_estimated_parent_remove_estimated_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimated',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.estimated', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='estimated',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
