# Generated by Django 5.2.9 on 2026-06-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_estimate_estimate_print_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='construction_name',
            new_name='construction',
        ),
    ]
