# Generated by Django 5.2.13 on 2026-06-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_user_short_name_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_no',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='担当者番号'),
        ),
    ]
