# Generated by Django 5.2.13 on 2026-06-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_user_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='manager_flg',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='現場管理職'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salesman_flg',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='営業職'),
        ),
    ]
