# Generated by Django 5.2.9 on 2026-07-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_construction_name_estimate_construction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='fiscalyear_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u3000年度名称'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='fiscalyear_no',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='年度コード'),
        ),
    ]
