# Generated by Django 5.2.9 on 2026-01-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_estimated_parent_estimated_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimated',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
