# Generated by Django 5.2.9 on 2026-05-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_task_calcu_cls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='calcu_cls',
            field=models.CharField(blank=True, default='0', null=True, verbose_name='計算区分'),
        ),
    ]
