# Generated by Django 5.2.9 on 2026-01-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_estimated_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimated',
            name='name',
        ),
        migrations.AlterField(
            model_name='estimated',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
