# Generated by Django 5.2.9 on 2026-06-18 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_manager_flg_alter_user_salesman_flg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('construction_no', models.CharField(blank=True, max_length=2, null=True, verbose_name='工事区分番号')),
                ('construction_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='工事区分名称')),
                ('user_short_name', models.CharField(blank=True, max_length=5, null=True, verbose_name='担当者略称')),
                ('create_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='作成者')),
                ('update_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='更新者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client', verbose_name='事業者')),
            ],
            options={
                'db_table': 'construction',
            },
        ),
    ]
