# Generated by Django 5.2.9 on 2026-05-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_task_calcu_cls'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
