# Generated by Django 5.2.9 on 2026-07-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_fiscalyear_fiscalyear_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='summary',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='備考'),
        ),
    ]
