# Generated by Django 5.2.9 on 2026-06-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_construction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='user_short_name',
        ),
    ]
