# Generated by Django 5.2.9 on 2026-01-09 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_estimated_name_alter_estimated_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimated',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.estimated', verbose_name='parent'),
        ),
    ]
