# Generated by Django 5.2.9 on 2026-05-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_unit_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='unit_no',
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='unit name'),
        ),
    ]
