# Generated by Django 5.2.9 on 2026-07-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_estimate_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='markup_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='掛率'),
        ),
    ]
