# Generated by Django 5.2.13 on 2026-07-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_client_markup_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_no',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='得意先管理番号'),
        ),
    ]
