# Generated by Django 5.2.13 on 2026-05-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_unit_unit_no_alter_unit_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
