# Generated by Django 5.2.13 on 2026-05-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_reference_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_no',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='unit No'),
        ),
    ]
