# Generated by Django 5.2.13 on 2026-07-28 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_customer_customer_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='aggregation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.aggregation', verbose_name='計算区分'),
        ),
    ]
