# Generated by Django 5.2.9 on 2026-05-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_unit_unit_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_no',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='unit No'),
        ),
    ]
