# Generated by Django 5.2.9 on 2026-01-09 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_estimated_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimated',
            name='seq_no',
        ),
    ]
