# Generated by Django 5.2.13 on 2026-07-29 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_task_aggregation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='calcu_cls',
        ),
    ]
