# Generated by Django 5.2.9 on 2026-08-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_task_calcu_cls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='estimate_year',
        ),
    ]
