# Generated by Django 5.2.13 on 2026-08-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_estimate_estimate_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='estimate_no',
            new_name='estimate',
        ),
    ]
