# Generated by Django 5.2.9 on 2026-01-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_estimated_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimated',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
