# Generated by Django 5.2.13 on 2026-08-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_estimate_no_task_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備考'),
        ),
    ]
