# Generated by Django 5.2.13 on 2026-09-11 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_task_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregation',
            name='calcu_cls',
        ),
    ]
