# Generated by Django 5.2.13 on 2026-09-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_aggregation_calcu_cls'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregation',
            name='calcu_cls',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='計算区分'),
        ),
    ]
