# Generated by Django 5.2.9 on 2026-01-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_estimated_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='unit name'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_no',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='unit No'),
        ),
    ]
