# Generated by Django 5.2.9 on 2026-01-30 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_unit_unit_name_alter_unit_unit_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimated',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.estimated', verbose_name='parent'),
        ),
    ]
