# Generated by Django 5.2.9 on 2026-01-31 08:33

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_estimated_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimated',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='estimated',
            name='position',
        ),
        migrations.AddField(
            model_name='estimated',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimated',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimated',
            name='parentId',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.estimated'),
        ),
        migrations.AddField(
            model_name='estimated',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimated',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimated',
            name='tree_seq',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
