# Generated by Django 5.2.9 on 2026-01-31 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_estimated_parent_remove_estimated_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimated',
            old_name='parentId',
            new_name='parent',
        ),
    ]
