# Generated by Django 5.2.9 on 2026-01-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_parentid_estimated_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimated',
            name='tree_seq',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
