# Generated by Django 5.2.9 on 2026-01-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_estimated_tree_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimated',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
