# Generated by Django 5.2.9 on 2026-01-31 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_estimated_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimated',
            old_name='parent',
            new_name='parentId',
        ),
    ]
