# Generated by Django 5.2.9 on 2026-01-31 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_parent_estimated_parentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimated',
            old_name='parentId',
            new_name='parent',
        ),
    ]
