# Generated by Django 5.2.9 on 2026-01-31 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rename_parentid_estimated_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimated',
            old_name='parent',
            new_name='parentId',
        ),
    ]
