# Generated by Django 5.2.9 on 2026-02-01 08:30

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_parent_estimated_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimated',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.estimated'),
        ),
        migrations.AlterField(
            model_name='estimated',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='estimated',
            name='parentId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
