# Generated by Django 5.2.9 on 2026-02-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_estimated_parent_alter_estimated_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimated',
            name='parentIndex',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
