# Generated by Django 5.2.9 on 2026-02-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_estimated_parentindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimated',
            name='calcu_cls',
            field=models.IntegerField(blank=True, null=True, verbose_name='計算区分'),
        ),
    ]
