# Generated by Django 5.2.9 on 2026-02-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_estimated_calcu_cls'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimated',
            name='child',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
