# Generated by Django 5.2.9 on 2026-02-06 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_estimated_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimated',
            name='child',
        ),
    ]
