# Generated by Django 5.2.9 on 2026-02-11 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_estimated_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimated',
            name='budget_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit2', to='app.unit', verbose_name='予算単位'),
        ),
        migrations.AlterField(
            model_name='estimated',
            name='calcu_cls',
            field=models.CharField(blank=True, null=True, verbose_name='計算区分'),
        ),
        migrations.CreateModel(
            name='DetailMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='明細名称')),
                ('calcu_cls', models.CharField(blank=True, null=True, verbose_name='計算区分')),
                ('budget_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='予算単価')),
                ('unit_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit1', to='app.unit', verbose_name='予算単位')),
            ],
            options={
                'db_table': 'detailMaster',
            },
        ),
    ]
