# Generated by Django 5.2.9 on 2026-02-13 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_reference_delete_detailmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimated',
            name='budget_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.unit', verbose_name='予算単位'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='unit_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.unit', verbose_name='予算単位'),
        ),
    ]
